USE nehemiah_inventory;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS position VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255) DEFAULT NULL; 